config/routes.rb
Rails.application.routes.draw do
  root 'comments#index'
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'comments/index'
  get 'comments/new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    #@comment = Comment.order("RANDOM()").first
    #@comment = Comment.all
  end
  
  def new
    @comment = Comment.new
  end

  def create
    Comment.create(comment_params)  
    redirect_to root_path 
  end

  private
  
  def comment_params
    params.require(:comment).permit(:description, :author)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<body>

  <div class="blog">
    <h1>Quiz</h1>
      <p>I have chosen to make a ruby app of my first blog post.</p>
      
    <h2>The Keys to Learning Something New</h2>    
      <p>
        Getting out of our comfort zones and learning something new is a challenge we all face. The below points will help you through the experience of learning something new.
      </p>
      
    <h3>The time to start learning is now!</h3>    
      <p>
        Don’t waste what could be years of learning . The longer you wait, the more time will pass. Start learning right away. The more you learn, the hungrier you will become and want to learn more. Once you have momentum, it’ll be easy to keep going.
      </p>  
      
    <h3>Read it today, understand it tomorrow.</h3>    
      <p>
        New information is overwhelming. You don’t have to understand everything you read overnight. Learn as much as you can and it will make more sense every time you see it. If you review something enough times, it will begin to look familiar and be easier to understand.
      </p>
      
    <h3>Focus on how much you’re learning, not how much you don’t know.</h3>    
      <p>
        You will feel very overwhelmed learning something new. You will feel like you are no where close to knowing it all. The truth is, it’s impossible to learn everything. If you focus on how much more you know today than you did yesterday, you will be happier and more motivated to learn more.
      </p>
      
      <p>
        If you follow these simple tips you will have an easier time learning and be less stressed!
      </p>       
  </end>

  <div class="col-10 links">
    <%= link_to 'Click here to comment on the blog!', new_comment_path %>      
  </div>
  <br />


    <div>
      <h1><%= @comment.description %></h1>
      <i><%= @comment.author %></i>
    </div>

  
  <br />
  <br />
  <br />

</body>

app/views/comments/new.html.erb
<div class="blog col-10">
  <h4>What do you think about the blog?</h4>
  <%= simple_form_for @comment do |f| %>
    <%= f.input :description %>
    <%= f.input :author %>
    <br />
    <%= f.submit 'Submit', class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>